cursor_trail 		1
cursor_trail_decay 0.2 	0.4
cursor_shape 		block
shell_integration 	no-cursor
cursor_blink_interval 	0.8

font_size 		14.0

map alt+h 		neighboring_window left
map alt+j 		neighboring_window bottom
map alt+k 		neighboring_window top
map alt+l 		neighboring_window right
map alt+shift+h 	move_window left
map alt+shift+j 	move_window bottom
map alt+shift+k 	move_window top
map alt+shift+l 	move_window right
map alt+r		layout_action rotate

map alt+1 		goto_tab 1
map alt+2 		goto_tab 2
map alt+3 		goto_tab 3
map alt+4 		goto_tab 4
map alt+5 		goto_tab 5
map alt+6 		goto_tab 6
map alt+7 		goto_tab 7
map alt+8 		goto_tab 8
map alt+9 		goto_tab 9
map alt+0 		goto_tab 10

enabled_layouts	         splits,stack

map alt+z 		toggle_layout stack
map alt+w 		close_window
map alt+d launch 	--cwd=current --location vsplit
map alt+shift+d launch  --cwd=current --location hsplit
map alt+t 		new_tab_with_cwd
map alt+m 		detach_window new-tab

enable_audio_bell 	no

include 		./dark-theme.auto.conf

map ctrl+shift+p 	send_text normal pwd | kitten clipboard \x0d


# disable_ligatures cursor
