cursor_trail  			1
cursor_trail_decay 		0.2 0.4
cursor_shape 			block
shell_integration 		no-cursor
cursor_blink_interval 		0

font_size 			14.0

map cmd+h 			neighboring_window left
map cmd+j 			neighboring_window bottom
map cmd+k 			neighboring_window top
map cmd+l 			neighboring_window right
map cmd+shift+h			move_window left
map cmd+shift+j			move_window bottom
map cmd+shift+k			move_window top
map cmd+shift+l			move_window right

map cmd+1 			goto_tab 1
map cmd+2 			goto_tab 2
map cmd+3 			goto_tab 3
map cmd+4 			goto_tab 4
map cmd+5 			goto_tab 5
map cmd+6 			goto_tab 6
map cmd+7 			goto_tab 7
map cmd+8 			goto_tab 8
map cmd+9 			goto_tab 9
map cmd+0 			goto_tab 10

enabled_layouts 		splits,stack

map cmd+z 			toggle_layout stack
map cmd+w 			close_window
map cmd+d            		launch --cwd=current --location vsplit
map cmd+shift+d  		launch --cwd=current --location hsplit
map alt+m               	detach_window new-tab

include                 	./dark-theme.auto.conf

enable_audio_bell		no

active_border_color     	#FFC0CB

copy_on_select			yes

map ctrl+shift+p        send_text normal pwd | kitten clipboard \x0d
